export const responseDataPermissionUsingRole: any = {
    admin: {
        user_locations: {
            stateCodes: null,
            districts: null,
        },
        user_role: [
            {
                role_slug: "admin",
            },
        ],
        user_department: [],
        user_type: [],
        user_number: [],
        user_role_permission: [
            {
                uuid: "dashboard-001",
                parent_id: "0",
                name: "Dashboard",
                slug: "dashboard",
                module_url: "/admin/dashboard",
                icon: "Dashboard",
                module_order: "1",
                is_navigation: 1,
            },
            {
                uuid: "leads-001",
                parent_id: "0",
                name: "Leads",
                slug: "leads",
                module_url: "/admin/leads",
                icon: "Groups",
                module_order: "2",
                is_navigation: 1,
            },
            {
                uuid: "deals-001",
                parent_id: "0",
                name: "Deals Pipeline",
                slug: "deals-pipeline",
                module_url: "/admin/deals-pipeline",
                icon: "ViewKanban",
                module_order: "3",
                is_navigation: 1,
            },
            {
                uuid: "contacts-001",
                parent_id: "0",
                name: "Contacts",
                slug: "contacts",
                module_url: "/admin/contacts",
                icon: "ContactPage",
                module_order: "4",
                is_navigation: 1,
            },
            {
                uuid: "activities-001",
                parent_id: "0",
                name: "Activities",
                slug: "activities",
                module_url: "/admin/activities",
                icon: "Timeline",
                module_order: "5",
                is_navigation: 1,
            },
            {
                uuid: "reports-001",
                parent_id: "0",
                name: "Reports",
                slug: "reports",
                module_url: "/admin/reports",
                icon: "BarChart",
                module_order: "6",
                is_navigation: 1,
            },
        ],
    },
};
